kind: Deployment
apiVersion: apps/v1
metadata:
  name: python-api
  labels:
    app: python-api
spec:
  selector:
    matchLabels:
      app: python-api
  replicas: 1
  template:
    metadata:
      labels:
        app: python-api
    spec:
      serviceAccount: s3-getput ## add service account
      containers:
      - image: rohitkalyan18/python-api:sha-147e05a68597e0d1b349fec334046aa8020c4fa8
        name: python-api
        ports:
        - containerPort: 8000
        env:
        # - name: AWS_ACCESS_KEY_ID
        #   valueFrom:
        #     secretKeyRef:
        #       name: aws
        #       key: AWS_ACCESS_KEY
        # - name: AWS_SECRET_ACCESS_KEY
        #   valueFrom:
        #     secretKeyRef:
        #       name: aws
        #       key: AWS_SECRET_ACCESS_KEY
        - name: BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: bucket-name
              key: bucket_name
        - name: AWS_REGION
          value: "us-east-1"